/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/IMIP_Placeholder.glb -t 
*/
// @ts-nocheck

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder001: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/IMIP_Placeholder.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} />
      <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} />
    </group>
  )
}

useGLTF.preload('/IMIP_Placeholder.glb')
