/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/IMIP_Placeholder.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/IMIP_Placeholder.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} />
      <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} />
    </group>
  )
}

useGLTF.preload('/IMIP_Placeholder.glb')
